// <auto-generated />
using System;
using AtlanticCity.Control.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtlanticCity.Control.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    [Migration("20260909052539_InitialLoadSchema")]
    partial class InitialLoadSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtlanticCity.Control.Domain.Loads.LoadError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_error");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("campo");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid")
                        .HasColumnName("carga_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mensaje");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_originales");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("numero_fila");

                    b.HasKey("Id");

                    b.HasIndex("LoadId")
                        .HasDatabaseName("ix_detalle_carga_error_carga_id");

                    b.ToTable("detalle_carga_error", (string)null);
                });

            modelBuilder.Entity("AtlanticCity.Control.Domain.Loads.LoadFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mensaje_error");

                    b.Property<int>("ExistingRows")
                        .HasColumnType("integer")
                        .HasColumnName("registros_existentes");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_archivo");

                    b.Property<int>("InsertedRows")
                        .HasColumnType("integer")
                        .HasColumnName("registros_insertados");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("integer")
                        .HasColumnName("registros_invalidos");

                    b.Property<DateTimeOffset?>("LoadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cargado");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_notificacion");

                    b.Property<string>("Period")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodo");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_proceso");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resultado");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ruta_archivo");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_registros");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario_email");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_id");

                    b.Property<int>("ValidRows")
                        .HasColumnType("integer")
                        .HasColumnName("registros_validos");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_carga_archivo_fecha_registro");

                    b.HasIndex("Period")
                        .HasDatabaseName("ix_carga_archivo_periodo");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_carga_archivo_usuario_id");

                    b.ToTable("carga_archivo", (string)null);
                });

            modelBuilder.Entity("AtlanticCity.Control.Domain.Loads.LoadStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid")
                        .HasColumnName("carga_id");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mensaje");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evento");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resultado");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.HasKey("Id");

                    b.HasIndex("LoadId", "OccurredAt")
                        .HasDatabaseName("ix_historial_estado_carga_carga_fecha");

                    b.ToTable("historial_estado_carga", (string)null);
                });

            modelBuilder.Entity("AtlanticCity.Control.Domain.Loads.ProcessedData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("categoria");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uuid")
                        .HasColumnName("carga_id");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodo");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_producto");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nombre_producto");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("numero_fila");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasDatabaseName("ux_data_procesada_codigo_producto");

                    b.HasIndex("LoadId", "SourceRowNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_data_procesada_carga_fila");

                    b.ToTable("data_procesada", (string)null);
                });

            modelBuilder.Entity("AtlanticCity.Control.Domain.Loads.LoadError", b =>
                {
                    b.HasOne("AtlanticCity.Control.Domain.Loads.LoadFile", null)
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtlanticCity.Control.Domain.Loads.LoadStatusHistory", b =>
                {
                    b.HasOne("AtlanticCity.Control.Domain.Loads.LoadFile", null)
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtlanticCity.Control.Domain.Loads.ProcessedData", b =>
                {
                    b.HasOne("AtlanticCity.Control.Domain.Loads.LoadFile", null)
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
